# 国际标准时间+8
# 每天 issue 新增情况
name: issues-dailyclose-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  create-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TDesignOteam/create-report@main
        with:
          wxhook: ${{ secrets.WX_HOOK_URL }}
          token: ${{ secrets.GIT_TOKEN_L }}
          type: 'new'
